In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from pandas import DataFrame
from tqdm import tqdm
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sample=pd.read_csv("Desktop/finalfeaturetrain.csv")

In [3]:
sample

Unnamed: 0      id  is_duplicate  qid1fre  qid2fre  q1len  q2len  \
0                0       0             0        1        1     66     57   
1                1       1             0        1        1     51     88   
2                2       2             0        1        1     73     59   
3                3       3             0        1        1     50     65   
4                4       4             0        1        1     76     39   
5                5       5             1        1        1     86     90   
6                6       6             0        1        1     19     62   
7                7       7             1        1        1     30     41   
8                8       8             0        1        1     35     37   
9                9       9             0        1        1     60     49   
10              10      10             0        1        1     57    116   
11              11      11             1        1        1     43     38   
12              12      12             1        1        1     36     39   
13              13      13             1        1        1     43     38   
14              14      14             0        1        1    141    140   
15              15      15             1        1        1     95     91   
16              16      16             1        1        1     28     29   
17              17      17             0        1        1     57     40   
18              18      18             1        1        1     82     73   
19              19      19             0        1        1     60     54   
20              20      20             1        1        1     26     43   
21              21      21             0        1        1     37     48   
22              22      22             0        1        1     47     37   
23              23      23             0        1        1     24     57   
24              24      24             0        1        1     79     50   
25              25      25             0        1        1     79     89   
26              26      26             0        1        1     24     38   
27              27      27             0        1        1     49     40   
28              28      28             0        1        1     38     41   
29              29      29             1        1        1     38     69   
...            ...     ...           ...      ...      ...    ...    ...   
404321      404321  404321             0        1        1     32     40   
404322      404322  404322             1        1        1     58     64   
404323      404323  404323             0        1        1     41     32   
404324      404324  404324             0        1        1     66     65   
404325      404325  404325             0        1        1     78     42   
404326      404326  404326             1        1        1     33     33   
404327      404327  404327             0        1        1     58    179   
404328      404328  404328             1        1        1     52     80   
404329      404329  404329             0        1        1     60     44   
404330      404330  404330             0        1        1     52     63   
404331      404331  404331             0        1        1     43     45   
404332      404332  404332             0        1        1     80     65   
404333      404333  404333             1        1        1     83     87   
404334      404334  404334             1        1        1     47     83   
404335      404335  404335             1        1        1     62     51   
404336      404336  404336             0        1        1     60     79   
404337      404337  404337             0        1        1     26     24   
404338      404338  404338             0        1        1     23     32   
404339      404339  404339             0        1        1     41     52   
404340      404340  404340             0        1        1     66     77   
404341      404341  404341             1        1       

In [4]:
sample=sample.dropna(axis=0)

In [5]:
sample

Unnamed: 0      id  is_duplicate  qid1fre  qid2fre  q1len  q2len  \
1                1       1             0        1        1     51     88   
3                3       3             0        1        1     50     65   
4                4       4             0        1        1     76     39   
5                5       5             1        1        1     86     90   
8                8       8             0        1        1     35     37   
9                9       9             0        1        1     60     49   
10              10      10             0        1        1     57    116   
12              12      12             1        1        1     36     39   
13              13      13             1        1        1     43     38   
14              14      14             0        1        1    141    140   
15              15      15             1        1        1     95     91   
18              18      18             1        1        1     82     73   
19              19      19             0        1        1     60     54   
20              20      20             1        1        1     26     43   
21              21      21             0        1        1     37     48   
23              23      23             0        1        1     24     57   
25              25      25             0        1        1     79     89   
27              27      27             0        1        1     49     40   
28              28      28             0        1        1     38     41   
29              29      29             1        1        1     38     69   
32              32      32             1        1        1     72     71   
36              36      36             0        1        1    115     76   
37              37      37             0        1        1    127    194   
38              38      38             1        1        1     27     35   
39              39      39             0        1        1     71     72   
40              40      40             0        1        1     19     33   
42              42      42             0        1        1     41     41   
43              43      43             0        1        1     67     30   
44              44      44             0        1        1     88     90   
45              45      45             0        1        1     57     54   
...            ...     ...           ...      ...      ...    ...    ...   
404306      404306  404306             0        1        1     66     89   
404308      404308  404308             1        1        1     72     74   
404310      404310  404310             1        1        1     54    110   
404311      404311  404311             0        1        1     77     39   
404312      404312  404312             0        1        1    114     73   
404313      404313  404313             0        1        1     42     44   
404314      404314  404314             0        1        1     38     41   
404315      404315  404315             0        1        1    142    170   
404317      404317  404317             0        1        1     63    101   
404318      404318  404318             1        1        1     38     26   
404319      404319  404319             1        1        1     69     59   
404322      404322  404322             1        1        1     58     64   
404323      404323  404323             0        1        1     41     32   
404324      404324  404324             0        1        1     66     65   
404326      404326  404326             1        1        1     33     33   
404327      404327  404327             0        1        1     58    179   
404328      404328  404328             1        1        1     52     80   
404330      404330  404330             0        1        1     52     63   
404332      404332  404332             0        1        1     80     65   
404333      404333  404333             1        1        1     83     87   
404334      404334  404334             1        1       

# Splitting of data

In [6]:
y=sample['is_duplicate']
X=sample.drop('is_duplicate',axis=1)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.neural_network import MLPRegressor

In [9]:
mlp=MLPRegressor(hidden_layer_sizes=(31,),activation='logistic',alpha=0.1)

In [10]:
mlp.fit(X_train,y_train)
mlppredict=mlp.predict(X_test)

In [11]:
mlppredict

array([0.37606426, 0.37606426, 0.37606426, ..., 0.3537114 , 0.37606426,
       0.37606426])

In [12]:
mlppredicted=mlppredict

In [13]:
for i in tqdm(range(0,len(mlppredict))):
    if mlppredict[i]<0.36:
        mlppredict[i]=0
    else:
        mlppredict[i]=1   

100%|███████████████████████████████████████████████████████████████████████| 89402/89402 [00:00<00:00, 1151800.95it/s]


In [15]:
mlppredicted

array([1., 1., 1., ..., 0., 1., 1.])

In [16]:
predi=DataFrame(mlppredict)

In [17]:
predi

0
0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
5      1.0
6      1.0
7      1.0
8      1.0
9      1.0
10     1.0
11     1.0
12     1.0
13     1.0
14     1.0
15     0.0
16     1.0
17     1.0
18     1.0
19     1.0
20     1.0
21     1.0
22     1.0
23     1.0
24     1.0
25     1.0
26     1.0
27     1.0
28     1.0
29     1.0
...    ...
89372  1.0
89373  1.0
89374  1.0
89375  1.0
89376  1.0
89377  1.0
89378  1.0
89379  1.0
89380  1.0
89381  1.0
89382  1.0
89383  1.0
89384  1.0
89385  1.0
89386  1.0
89387  1.0
89388  1.0
89389  1.0
89390  1.0
89391  1.0
89392  1.0
89393  1.0
89394  1.0
89395  1.0
89396  1.0
89397  1.0
89398  1.0
89399  0.0
89400  1.0
89401  1.0

[89402 rows x 1 columns]

In [39]:
predi.columns=['predicted']

In [40]:
predi

predicted
0           1.0
1           0.0
2           0.0
3           0.0
4           0.0
5           0.0
6           0.0
7           1.0
8           0.0
9           0.0
10          1.0
11          1.0
12          1.0
13          1.0
14          0.0
15          1.0
16          1.0
17          0.0
18          0.0
19          1.0
20          1.0
21          1.0
22          1.0
23          1.0
24          1.0
25          1.0
26          1.0
27          1.0
28          1.0
29          1.0
...         ...
8303        1.0
8304        0.0
8305        1.0
8306        1.0
8307        1.0
8308        1.0
8309        1.0
8310        0.0
8311        0.0
8312        0.0
8313        1.0
8314        1.0
8315        0.0
8316        0.0
8317        0.0
8318        0.0
8319        1.0
8320        0.0
8321        1.0
8322        1.0
8323        0.0
8324        0.0
8325        0.0
8326        0.0
8327        1.0
8328        0.0
8329        0.0
8330        0.0
8331        1.0
8332        0.0

[8333 rows x 1 columns]

In [45]:
len(y_test)

8333

In [43]:
real=DataFrame(y_test)

In [46]:
real=DataFrame(y_test)

In [50]:
final=pd.concat([real,predi],axis=1)

In [51]:
final

is_duplicate  predicted
0                1        1.0
1                0        0.0
2                0        0.0
3                0        0.0
4                0        0.0
5                0        0.0
6                0        0.0
7                1        1.0
8                0        0.0
9                0        0.0
10               1        1.0
11               0        1.0
12               0        1.0
13               1        1.0
14               0        0.0
15               0        1.0
16               0        1.0
17               0        0.0
18               0        0.0
19               0        1.0
20               1        1.0
21               0        1.0
22               1        1.0
23               1        1.0
24               0        1.0
25               0        1.0
26               0        1.0
27               1        1.0
28               1        1.0
29               0        1.0
...            ...        ...
8303             0        1.0
8304             0        0.0
8305             0        1.0
8306             0        1.0
8307             0        1.0
8308             1        1.0
8309             1        1.0
8310             0        0.0
8311             0        0.0
8312             0        0.0
8313             0        1.0
8314             0        1.0
8315             0        0.0
8316             0        0.0
8317             1        0.0
8318             0        0.0
8319             0        1.0
8320             0        0.0
8321             0        1.0
8322             0        1.0
8323             0        0.0
8324             0        0.0
8325             0        0.0
8326             1        0.0
8327             0        1.0
8328             0        0.0
8329             0        0.0
8330             0        0.0
8331             0        1.0
8332             0        0.0

[8333 rows x 2 columns]

In [54]:
neural=confusion_matrix(final['is_duplicate'],final['predicted'])
neural

array([[2952, 2237],
       [ 729, 2415]], dtype=int64)

In [55]:
accuracy=(2952+2415)/(2952+2237+729+2415)
accuracy

0.6440657626305052

In [62]:
mlp=MLPRegressor(hidden_layer_sizes=(50,),activation='logistic',alpha=0.1)
mlp.fit(X_train,y_train)
mlppredict=mlp.predict(X_test)
for i in tqdm(range(0,len(mlppredict))):
    if mlppredict[i]<0.50:
        mlppredict[i]=0
    else:
        mlppredict[i]=1   


100%|██████████████████████████████████████████████████████████████████████████| 8333/8333 [00:00<00:00, 835491.96it/s]


In [61]:
predi=DataFrame(mlppredict)  
predi.columns=['predicted']
real=DataFrame(y_test)
final=pd.concat([real,predi],axis=1)

is_duplicate  predicted
0               NaN        0.0
1               NaN        0.0
2               NaN        0.0
3               1.0        0.0
4               NaN        0.0
5               NaN        0.0
6               0.0        0.0
7               NaN        0.0
8               NaN        0.0
9               NaN        0.0
10              NaN        0.0
11              NaN        0.0
12              NaN        0.0
13              NaN        0.0
14              NaN        0.0
15              NaN        0.0
16              NaN        0.0
17              0.0        0.0
18              NaN        0.0
19              NaN        0.0
20              NaN        0.0
21              NaN        0.0
22              NaN        0.0
23              NaN        0.0
24              NaN        0.0
25              NaN        0.0
26              NaN        0.0
27              NaN        0.0
28              NaN        0.0
29              0.0        0.0
...             ...        ...
25168           1.0        NaN
25171           1.0        NaN
25172           1.0        NaN
25176           0.0        NaN
25180           1.0        NaN
25181           0.0        NaN
25183           0.0        NaN
25185           0.0        NaN
25192           1.0        NaN
25193           0.0        NaN
25194           0.0        NaN
25197           0.0        NaN
25201           1.0        NaN
25205           1.0        NaN
25206           0.0        NaN
25208           0.0        NaN
25209           0.0        NaN
25211           1.0        NaN
25212           0.0        NaN
25213           0.0        NaN
25214           0.0        NaN
25217           0.0        NaN
25218           1.0        NaN
25221           0.0        NaN
25233           0.0        NaN
25234           1.0        NaN
25236           0.0        NaN
25237           1.0        NaN
25245           0.0        NaN
25247           0.0        NaN

[13912 rows x 2 columns]

In [63]:
mlppredict

array([0., 0., 0., ..., 0., 0., 0.])

In [13]:
from sklearn.neural_network import MLPClassifier

In [21]:
clf = MLPClassifier( hidden_layer_sizes=(780,),activation='logistic', alpha=0.1)

In [22]:
clf.fit(X_train,y_train)
clfpredict=clf.predict(X_test)

In [23]:
predict=pd.DataFrame(clfpredict)

In [18]:
y_test

246904    0
312585    1
220382    1
234607    0
76873     0
133294    0
299933    0
117527    0
313331    1
95831     1
100624    0
388318    0
204110    0
382250    1
10086     1
1664      1
357433    0
41195     0
306750    0
66693     0
319687    1
64840     0
93069     1
132798    1
169091    1
15225     1
204473    1
286784    0
394210    1
276028    0
         ..
233545    0
366676    1
11627     0
170455    1
5898      0
231425    0
69007     1
59512     1
275432    1
241059    0
54241     1
179816    0
51793     0
297981    1
158652    0
252801    0
51357     0
369458    1
305277    0
12505     0
49089     0
199685    0
132963    1
273658    0
287232    0
62391     0
267385    1
2575      0
113643    1
7500      1
Name: is_duplicate, Length: 89402, dtype: int64

In [24]:
predict

0
0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
...   ..
89372  0
89373  0
89374  0
89375  0
89376  0
89377  0
89378  0
89379  0
89380  0
89381  0
89382  0
89383  0
89384  0
89385  0
89386  0
89387  0
89388  0
89389  0
89390  0
89391  0
89392  0
89393  0
89394  0
89395  0
89396  0
89397  0
89398  0
89399  0
89400  0
89401  0

[89402 rows x 1 columns]